#!/bin/bash -e

# alidock-installer -- simplify the installation of alidock
#
# This Bash script simplifies the installation of alidock by using a Python
# virtualenv. We make sure we are using our own isolated Python environment for
# it, and it should work seamlessly without being root.

VIRTUALENV_VERSION=16.1.0
TMPDIR=$(mktemp -d /tmp/alidock-installer-XXXXX)
VENV_DEST="$HOME/.virtualenvs/alidock"

function pinfo() { echo -e "\033[32m${1}\033[m"; }
function perr() { echo -e "\033[31m${1}\033[m"; }
function pwarn() { echo -e "\033[33m${1}\033[m"; }
function swallow() {
  local ERR=0
  "$@" &> "$TMPDIR/log" || ERR=$?
  if [[ $ERR != 0 ]]; then
    cat "$TMPDIR/log"
  else
    rm -f "$TMPDIR/log"
  fi
  return $ERR
}

cd /
rm -rf "$VENV_DEST"  # always start from scratch

# Favour `python3`, fall back on `python`
PYTHON_BIN=python3
type "$PYTHON_BIN" &> /dev/null || PYTHON_BIN=python
if ! type "$PYTHON_BIN" &> /dev/null; then
  perr "It appears Python is not available on your system: cannot continue"
  exit 1
fi

pushd "$TMPDIR" &> /dev/null
  pinfo "Creating an environment for alidock using $("$PYTHON_BIN" --version 2>&1 | grep Python) ("$PYTHON_BIN")"
  curl -Lso - https://github.com/pypa/virtualenv/tarball/${VIRTUALENV_VERSION} | tar xzf -
  swallow "$PYTHON_BIN" pypa-virtualenv-*/src/virtualenv.py "$VENV_DEST"
popd &> /dev/null

pinfo "Installing alidock under $VENV_DEST"
swallow source "$VENV_DEST/bin/activate"
swallow pip install --upgrade alidock

# Patch init scripts for bash and zsh
SHELLRC="$HOME/.bashrc"
SHELL_CHANGED=
for SHELLRC in $HOME/.bashrc $HOME/.bash_profile $HOME/.zshrc; do
  if ! grep -q 'function alidock()' "$SHELLRC" &> /dev/null; then
    pinfo "Adding alidock to $SHELLRC"
    touch "$SHELLRC"
    if [[ $(tail -c 1 "$SHELLRC") ]]; then
      echo >> "$SHELLRC"
    fi
    echo '# Execute alidock within the appropriate Python virtual environment' >> "$SHELLRC"
    echo 'function alidock() {( source "'$VENV_DEST'/bin/activate" && command alidock "$@"; exit $?; )}' >> "$SHELLRC"
    SHELL_CHANGED=1
  fi
done

pinfo "Installed: $(alidock --version)"

if [[ $SHELL_CHANGED ]]; then
  pwarn "Please open a new shell (terminal window, tab, etc.) in order to use alidock."
  pwarn "When you are done, you can use it by typing:"
  pwarn "    alidock"
else
  pwarn "You can use alidock by simply typing:"
  pwarn "    alidock"
fi

rm -rf "$TMPDIR"
